import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatInrFull, type VendorLabel, type VendorMeta } from "./format";

type TableRow = Record<string, unknown>;

type SubGroup = { sub: string; rows: TableRow[] };
type CatGroup = { category: string; subs: SubGroup[] };

function groupTableData(rows: TableRow[]): CatGroup[] {
  const cats: CatGroup[] = [];
  const catIdx = new Map<string, number>();
  const subIdx = new Map<string, number>();

  for (const item of rows) {
    const category = String(item.category || "Other");
    const sub = String(item.sub_service || "General");

    if (!catIdx.has(category)) {
      catIdx.set(category, cats.length);
      cats.push({ category, subs: [] });
    }
    const cat = cats[catIdx.get(category)!];

    const subKey = `${category}||${sub}`;
    if (!subIdx.has(subKey)) {
      subIdx.set(subKey, cat.subs.length);
      cat.subs.push({ sub, rows: [] });
    }
    cat.subs[subIdx.get(subKey)!].rows.push(item);
  }
  return cats;
}

function formatPrice(value: unknown): string {
  if (value === 0 || value === undefined || value === null) return "N/A";
  return `₹${Number(value).toLocaleString("en-IN")}`;
}

function vendorHeaderCell(
  vendor: string,
  vendorLabels: Record<string, VendorLabel>,
  vendorMeta: Record<string, VendorMeta>
): string {
  const info = vendorLabels[vendor];
  const meta = vendorMeta[vendor] || {};
  const company = info?.company ?? vendor.split(" (")[0];
  const lines = [company];
  if (info?.variant) lines.push(info.variant);
  const qno = info?.quoteNumber ? `#${info.quoteNumber}` : "";
  const qdate = info?.quoteDate || meta.quote_date || "";
  if (qno || qdate) lines.push([qno, qdate].filter(Boolean).join(" · "));
  return lines.join("\n");
}

/** Generate and download comparison matrix PDF directly (no print dialog). */
export function downloadComparisonPdf(
  tableData: TableRow[],
  vendors: string[],
  vendorLabels: Record<string, VendorLabel>,
  vendorMeta: Record<string, VendorMeta> = {}
): void {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 10;

  const today = new Date().toLocaleDateString("en-IN", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Tatva Quotes Comparison Matrix", margin, 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by QuoteSense · ${today}`, margin, 19);
  doc.setTextColor(0, 0, 0);

  const vendorHeaders = vendors.map((v) =>
    vendorHeaderCell(v, vendorLabels, vendorMeta)
  );
  const head = [["Service Description", "Moving Avg", ...vendorHeaders]];

  type BodyCell =
    | string
    | {
        content: string;
        colSpan: number;
        styles?: Record<string, unknown>;
      };

  const body: BodyCell[][] = [];

  for (const cat of groupTableData(tableData)) {
    body.push([
      {
        content: cat.category,
        colSpan: vendors.length + 2,
        styles: {
          fillColor: [238, 242, 255],
          textColor: [30, 58, 138],
          fontStyle: "bold",
          fontSize: 9,
          cellPadding: { top: 3, bottom: 3, left: 4, right: 4 },
        },
      },
    ]);
    for (const sub of cat.subs) {
      body.push([
        {
          content: sub.sub,
          colSpan: vendors.length + 2,
          styles: {
            fillColor: [248, 250, 252],
            textColor: [100, 116, 139],
            fontStyle: "bold",
            fontSize: 8,
            cellPadding: { top: 2, bottom: 2, left: 6, right: 4 },
          },
        },
      ]);
      for (const row of sub.rows) {
        const avg = Number(row.moving_average ?? row.market_average) || 0;
        const weight = Number(row.moving_weight) || 0;
        let avgText = avg > 0 ? formatInrFull(avg) : "—";
        if (weight > 0) avgText += `\n(${weight} quotes)`;

        const name = String(row.item_name || row.work_item || row.sub_service || "");
        const room = row.room ? `\n${String(row.room).toUpperCase()}` : "";

        body.push([
          name + room,
          avgText,
          ...vendors.map((v) => formatPrice(row[v])),
        ]);
      }
    }
  }

  const descWidth = 78;
  const avgWidth = 34;
  const vendorWidth = (pageWidth - margin * 2 - descWidth - avgWidth) / vendors.length;

  const columnStyles: Record<number, { cellWidth: number; halign?: "right" | "left" }> = {
    0: { cellWidth: descWidth },
    1: { cellWidth: avgWidth, halign: "right" },
  };
  vendors.forEach((_, i) => {
    columnStyles[i + 2] = { cellWidth: vendorWidth, halign: "right" };
  });

  autoTable(doc, {
    head,
    body: body as Parameters<typeof autoTable>[1]["body"],
    startY: 24,
    margin: { left: margin, right: margin, top: 24, bottom: 12 },
    theme: "grid",
    styles: {
      fontSize: 8,
      cellPadding: 2.5,
      overflow: "linebreak",
      valign: "middle",
      lineColor: [226, 232, 240],
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: [248, 250, 252],
      textColor: [15, 23, 42],
      fontStyle: "bold",
      fontSize: 7.5,
      minCellHeight: 12,
    },
    columnStyles,
    showHead: "everyPage",
    rowPageBreak: "avoid",
  });

  doc.save("comparator.pdf");
}
