import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { type VendorLabel, type VendorMeta } from "./format";

/** jsPDF built-in serif — closest to Times New Roman (Calibri needs custom embed). */
const FONT = "times";

type TableRow = Record<string, unknown>;

type SubGroup = { sub: string; rows: TableRow[] };
type CatGroup = { category: string; subs: SubGroup[] };

function groupTableData(rows: TableRow[]): CatGroup[] {
  const cats: CatGroup[] = [];
  const catIdx = new Map<string, number>();
  const subIdx = new Map<string, number>();

  for (const item of rows) {
    const category = String(item.category || "Other");
    const sub = String(item.sub_service || "General");

    if (!catIdx.has(category)) {
      catIdx.set(category, cats.length);
      cats.push({ category, subs: [] });
    }
    const cat = cats[catIdx.get(category)!];

    const subKey = `${category}||${sub}`;
    if (!subIdx.has(subKey)) {
      subIdx.set(subKey, cat.subs.length);
      cat.subs.push({ sub, rows: [] });
    }
    cat.subs[subIdx.get(subKey)!].rows.push(item);
  }
  return cats;
}

/** ASCII-safe currency — avoids broken ₹ glyph in standard PDF fonts. */
function formatPdfAmount(value: number): string {
  const n = Number(value);
  if (!Number.isFinite(n)) return "N/A";
  const formatted = n.toLocaleString("en-IN", {
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  });
  return `Rs. ${formatted}`;
}

function formatPdfPrice(value: unknown): string {
  if (value === 0 || value === undefined || value === null) return "N/A";
  return formatPdfAmount(Number(value));
}

function truncate(text: string, maxLen: number): string {
  const t = text.trim();
  if (t.length <= maxLen) return t;
  return `${t.slice(0, maxLen - 1)}…`;
}

function vendorHeaderCell(
  vendor: string,
  vendorLabels: Record<string, VendorLabel>,
  vendorMeta: Record<string, VendorMeta>
): string {
  const info = vendorLabels[vendor];
  const meta = vendorMeta[vendor] || {};
  const company = truncate(info?.company ?? vendor.split(" (")[0], 32);
  const lines = [company];
  if (info?.variant) lines.push(truncate(info.variant, 28));
  const qno = info?.quoteNumber ? `#${info.quoteNumber}` : "";
  const qdate = info?.quoteDate || meta.quote_date || "";
  if (qno || qdate) lines.push([qno, qdate].filter(Boolean).join(" · "));
  return lines.join("\n");
}

function buildColumnStyles(
  vendors: string[],
  tableWidth: number
): Record<number, { cellWidth: number; halign?: "right" | "left" }> {
  const descWidth = Math.min(68, tableWidth * 0.26);
  const avgWidth = 24;
  const vendorWidth = (tableWidth - descWidth - avgWidth) / Math.max(vendors.length, 1);

  const styles: Record<number, { cellWidth: number; halign?: "right" | "left" }> = {
    0: { cellWidth: descWidth, halign: "left" },
    1: { cellWidth: avgWidth, halign: "right" },
  };
  vendors.forEach((_, i) => {
    styles[i + 2] = { cellWidth: vendorWidth, halign: "right" };
  });
  return styles;
}

/** Generate and download comparison matrix PDF directly (no print dialog). */
export function downloadComparisonPdf(
  tableData: TableRow[],
  vendors: string[],
  vendorLabels: Record<string, VendorLabel>,
  vendorMeta: Record<string, VendorMeta> = {}
): void {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 12;
  const tableWidth = pageWidth - margin * 2;

  const today = new Date().toLocaleDateString("en-IN", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  doc.setFont(FONT, "bold");
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text("Tatva Quotes Comparison Matrix", margin, 14);
  doc.setFont(FONT, "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated by QuoteSense · ${today}`, margin, 19);
  doc.setTextColor(0, 0, 0);

  const vendorHeaders = vendors.map((v) =>
    vendorHeaderCell(v, vendorLabels, vendorMeta)
  );
  const head = [["Service Description", "Moving Avg", ...vendorHeaders]];

  type BodyCell =
    | string
    | {
        content: string;
        colSpan: number;
        styles?: Record<string, unknown>;
      };

  const body: BodyCell[][] = [];

  for (const cat of groupTableData(tableData)) {
    body.push([
      {
        content: cat.category.toUpperCase(),
        colSpan: vendors.length + 2,
        styles: {
          font: FONT,
          fillColor: [238, 242, 255],
          textColor: [30, 58, 138],
          fontStyle: "bold",
          fontSize: 8,
          cellPadding: { top: 2.5, bottom: 2.5, left: 4, right: 4 },
        },
      },
    ]);
    for (const sub of cat.subs) {
      body.push([
        {
          content: sub.sub.toUpperCase(),
          colSpan: vendors.length + 2,
          styles: {
            font: FONT,
            fillColor: [248, 250, 252],
            textColor: [100, 116, 139],
            fontStyle: "bold",
            fontSize: 7,
            cellPadding: { top: 2, bottom: 2, left: 6, right: 4 },
          },
        },
      ]);
      for (const row of sub.rows) {
        const avg = Number(row.moving_average ?? row.market_average) || 0;
        const weight = Number(row.moving_weight) || 0;
        let avgText = avg > 0 ? formatPdfAmount(avg) : "—";
        if (weight > 0) avgText += `\n(${weight} quotes)`;

        const name = String(row.item_name || row.work_item || row.sub_service || "");
        const room = row.room ? `\n${String(row.room)}` : "";

        body.push([
          name + room,
          avgText,
          ...vendors.map((v) => formatPdfPrice(row[v])),
        ]);
      }
    }
  }

  const columnStyles = buildColumnStyles(vendors, tableWidth);

  autoTable(doc, {
    head,
    body: body as Parameters<typeof autoTable>[1]["body"],
    startY: 23,
    tableWidth,
    margin: { left: margin, right: margin, top: 23, bottom: 14 },
    theme: "grid",
    styles: {
      font: FONT,
      fontSize: 7,
      cellPadding: { top: 2, bottom: 2, left: 3, right: 3 },
      overflow: "linebreak",
      valign: "middle",
      lineColor: [203, 213, 225],
      lineWidth: 0.15,
      textColor: [30, 41, 59],
    },
    headStyles: {
      font: FONT,
      fillColor: [241, 245, 249],
      textColor: [15, 23, 42],
      fontStyle: "bold",
      fontSize: 6.5,
      minCellHeight: 14,
      cellPadding: { top: 2, bottom: 2, left: 2, right: 2 },
      overflow: "linebreak",
    },
    bodyStyles: {
      font: FONT,
      fontSize: 7,
    },
    columnStyles,
    showHead: "everyPage",
    rowPageBreak: "avoid",
    horizontalPageBreak: false,
  });

  doc.save("comparator.pdf");
}
