-- Seed Interiors base rates (ESSENTIAL / MID_SEGMENT / LUXURY)
-- Spreadsheet names mapped to PM catalog (exact case).
-- LUXURY = MID_SEGMENT * 1.5 (not 2.5).
-- weight=0 seed until finalized quotes; rate columns = Recommended Base Rate
-- Skipped (no PM catalog match): Breakfast Counter, Deep Cleaning

BEGIN;

DELETE FROM public.market_moving_avg_sessions;
DELETE FROM public.market_moving_averages;

INSERT INTO public.market_moving_averages (
  service_type, service_category, sub_service, pricing_method,
  item_key, moving_average, rate_moving_average, weight, last_session_id
) VALUES
  ('ESSENTIAL', 'Interiors', 'Base Unit', 'Area (sqft)',
   'Base Unit::Area (sqft)', 1500.00, 1500.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Base Unit', 'Area (sqft)',
   'Base Unit::Area (sqft)', 2250.00, 2250.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Base Unit', 'Area (sqft)',
   'Base Unit::Area (sqft)', 3375.00, 3375.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Middle unit', 'Area (sqft)',
   'Middle unit::Area (sqft)', 1500.00, 1500.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Middle unit', 'Area (sqft)',
   'Middle unit::Area (sqft)', 2250.00, 2250.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Middle unit', 'Area (sqft)',
   'Middle unit::Area (sqft)', 3375.00, 3375.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Wall Unit', 'Area (sqft)',
   'Wall Unit::Area (sqft)', 1500.00, 1500.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Wall Unit', 'Area (sqft)',
   'Wall Unit::Area (sqft)', 2250.00, 2250.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Wall Unit', 'Area (sqft)',
   'Wall Unit::Area (sqft)', 3375.00, 3375.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Loft', 'Area (sqft)',
   'Loft::Area (sqft)', 800.00, 800.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Loft', 'Area (sqft)',
   'Loft::Area (sqft)', 1200.00, 1200.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Loft', 'Area (sqft)',
   'Loft::Area (sqft)', 1800.00, 1800.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'TV Units', 'Area (sqft)',
   'TV Units::Area (sqft)', 1400.00, 1400.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'TV Units', 'Area (sqft)',
   'TV Units::Area (sqft)', 2100.00, 2100.00, 0, NULL),
  ('LUXURY', 'Interiors', 'TV Units', 'Area (sqft)',
   'TV Units::Area (sqft)', 3150.00, 3150.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Crockery Units', 'Area (sqft)',
   'Crockery Units::Area (sqft)', 1400.00, 1400.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Crockery Units', 'Area (sqft)',
   'Crockery Units::Area (sqft)', 2100.00, 2100.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Crockery Units', 'Area (sqft)',
   'Crockery Units::Area (sqft)', 3150.00, 3150.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Wardrobe', 'Area (sqft)',
   'Wardrobe::Area (sqft)', 1400.00, 1400.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Wardrobe', 'Area (sqft)',
   'Wardrobe::Area (sqft)', 2100.00, 2100.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Wardrobe', 'Area (sqft)',
   'Wardrobe::Area (sqft)', 3150.00, 3150.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Dressing Unit', 'Area (sqft)',
   'Dressing Unit::Area (sqft)', 1400.00, 1400.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Dressing Unit', 'Area (sqft)',
   'Dressing Unit::Area (sqft)', 2100.00, 2100.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Dressing Unit', 'Area (sqft)',
   'Dressing Unit::Area (sqft)', 3150.00, 3150.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Vanity Units', 'Area (sqft)',
   'Vanity Units::Area (sqft)', 1500.00, 1500.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Vanity Units', 'Area (sqft)',
   'Vanity Units::Area (sqft)', 2250.00, 2250.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Vanity Units', 'Area (sqft)',
   'Vanity Units::Area (sqft)', 3375.00, 3375.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Study Table', 'Area (sqft)',
   'Study Table::Area (sqft)', 1100.00, 1100.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Study Table', 'Area (sqft)',
   'Study Table::Area (sqft)', 1650.00, 1650.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Study Table', 'Area (sqft)',
   'Study Table::Area (sqft)', 2475.00, 2475.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Wall Panels', 'Area (sqft)',
   'Wall Panels::Area (sqft)', 800.00, 800.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Wall Panels', 'Area (sqft)',
   'Wall Panels::Area (sqft)', 1200.00, 1200.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Wall Panels', 'Area (sqft)',
   'Wall Panels::Area (sqft)', 1800.00, 1800.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Bottle Pullouts', 'Per Unit',
   'Bottle Pullouts::Per Unit', 4500.00, 4500.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Bottle Pullouts', 'Per Unit',
   'Bottle Pullouts::Per Unit', 6750.00, 6750.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Bottle Pullouts', 'Per Unit',
   'Bottle Pullouts::Per Unit', 10125.00, 10125.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Tandem channels', 'Per Unit',
   'Tandem channels::Per Unit', 980.00, 980.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Tandem channels', 'Per Unit',
   'Tandem channels::Per Unit', 1470.00, 1470.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Tandem channels', 'Per Unit',
   'Tandem channels::Per Unit', 2205.00, 2205.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Rolling Shutter', 'Per Unit',
   'Rolling Shutter::Per Unit', 10500.00, 10500.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Rolling Shutter', 'Per Unit',
   'Rolling Shutter::Per Unit', 15750.00, 15750.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Rolling Shutter', 'Per Unit',
   'Rolling Shutter::Per Unit', 23625.00, 23625.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'PVC Tray and Thali', 'Per Unit',
   'PVC Tray and Thali::Per Unit', 600.00, 600.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'PVC Tray and Thali', 'Per Unit',
   'PVC Tray and Thali::Per Unit', 900.00, 900.00, 0, NULL),
  ('LUXURY', 'Interiors', 'PVC Tray and Thali', 'Per Unit',
   'PVC Tray and Thali::Per Unit', 1350.00, 1350.00, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Shoe Rack', 'Area (sqft)',
   'Shoe Rack::Area (sqft)', 1550.00, 1550.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Shoe Rack', 'Area (sqft)',
   'Shoe Rack::Area (sqft)', 2325.00, 2325.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Shoe Rack', 'Area (sqft)',
   'Shoe Rack::Area (sqft)', 3487.50, 3487.50, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Pooja Unit', 'Area (sqft)',
   'Pooja Unit::Area (sqft)', 1550.00, 1550.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Pooja Unit', 'Area (sqft)',
   'Pooja Unit::Area (sqft)', 2325.00, 2325.00, 0, NULL),
  ('LUXURY', 'Interiors', 'Pooja Unit', 'Area (sqft)',
   'Pooja Unit::Area (sqft)', 3487.50, 3487.50, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'False Ceiling', 'Area (sqft)',
   'False Ceiling::Area (sqft)', 105.00, 105.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'False Ceiling', 'Area (sqft)',
   'False Ceiling::Area (sqft)', 157.50, 157.50, 0, NULL),
  ('LUXURY', 'Interiors', 'False Ceiling', 'Area (sqft)',
   'False Ceiling::Area (sqft)', 236.25, 236.25, 0, NULL),
  ('ESSENTIAL', 'Interiors', 'Wallpaper', 'Area (sqft)/Per Unit',
   'Wallpaper::Area (sqft)/Per Unit', 75.00, 75.00, 0, NULL),
  ('MID_SEGMENT', 'Interiors', 'Wallpaper', 'Area (sqft)/Per Unit',
   'Wallpaper::Area (sqft)/Per Unit', 112.50, 112.50, 0, NULL),
  ('LUXURY', 'Interiors', 'Wallpaper', 'Area (sqft)/Per Unit',
   'Wallpaper::Area (sqft)/Per Unit', 168.75, 168.75, 0, NULL);

COMMIT;

-- Verify
SELECT service_type, count(*) FROM public.market_moving_averages GROUP BY 1 ORDER BY 1;
-- expect 19 each; LUXURY Base Unit should be 3375.00
